name: Push and publish version branch

on:
  push:
    branches:
      - 'v**'

jobs:
  build-and-deploy:
    uses: molant/electronjs.org-new/.github/workflows/build-and-deploy.yml@v1
    with:
      locale: en
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SAS: ${{ secrets.SAS }}
